trigger: none

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps/devops-pipeline-cicd
      ref: 'refs/heads/feature/segmentacion_templates'

stages:
  - template: build-validation.yaml@templates