trigger:
  branches:
    include:
      - "*"

resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps/devops-pipeline-cicd
      ref: 'refs/heads/feature/segmentacion_templates'

stages:
  - template: tasks/build-validation.yaml@templates